project:
  type: default
  output-dir: report
  post-render:
    - Rscript scripts/quarto_post_render_cleanup.R

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    number-sections: true
    link-external-newwindow: true

execute:
  warning: false
  message: false
