project:
  type: default
  output-dir: public

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    number-sections: true
    link-external-newwindow: true

execute:
  warning: false
  message: false
